(* An identifier can only be a bare key, matching  *)
identifier = bare_char, { bare_char } ;

(* Allowed characters: alphanumeric, underscore, and hyphen *)
bare_char  = alpha_char | digit | "_" | "-" ;

(* Base Whitespace Primitives (Unicode Hex Escape Notation) *)
space           = "\u{0020}" ;  (* Space Character *)
tab             = "\u{0009}" ;  (* Horizontal Tab *)

(* Line Ending Primitives *)
carriage_return = "\u{000D}" ;  (* CR *)
line_feed            = "\u{000A}" ;  (* LF *)
newline               = line_feed | carriage_return, line_feed ;

(* Structural Layout Rules *)
indentation     = { space | tab } ;
inline_ws       = { space | tab } ;

alpha_char     = lowercase_char | uppercase_char ;
digit          = "0" .. "9" ;
lowercase_char = "a" .. "z" ;
uppercase_char = "A" .. "Z" ;
